export default [
  {
    id: 1,
    img: "login.jpg",
    name: "Mango",
    capital: "50",
    quantity: "5",
    purchase: "Add to cart",
  },
  {
    id: 2,
    img: "login.jpg",
    name: "Apple",
    capital: "60",
    quantity: "1",
    purchase: "Add to cart",
  },
  {
    id: 3,
    img: "login.jpg",
    name: "orange",
    capital: "70",
    quantity: "3",
    purchase: "Add to cart",
  },
  {
    id: 4,
    img: "login.jpg",
    name: "Pineapple",
    capital: "80",
    quantity: "7",
    purchase: "Add to cart",
  },
  {
    id: 5,
    img: "login.jpg",
    name: "Palms",
    capital: "90",
    quantity: "9",
    purchase: "Add to cart",
  },
  {
    id: 6,
    img: "login.jpg",
    name: "Banana",
    capital: "56",
    quantity: "7",
    purchase: "Add to cart",
  },
  {
    id: 7,
    img: "login.jpg",
    name: "Lemon",
    capital: "25",
    quantity: "2",
    purchase: "Add to cart",
  },
  {
    id: 8,
    img: "login.jpg",
    name: "Water Melon",
    capital: "67",
    quantity: "8",
    purchase: "Add to cart",
  },
  {
    id: 9,
    img: "login.jpg",
    name: "Grape",
    capital: "73",
    quantity: "5",
    purchase: "Add to cart",
  },
  {
    id: 10,
    img: "login.jpg",
    name: "Passion",
    capital: "89",
    quantity: "3",
    purchase: "Add to cart",
  },
  {
    id: 11,
    img: "login.jpg",
    name: "Pawpaw",
    capital: "99",
    quantity: "9",
    purchase: "Add to cart",
  },
  // {
  //   id: 12,
  //   img: "login.jpg",
  //   name: "Jackfruit",
  //   capital: "10",
  //   quantity: "7",
  //   purchase: "Add to cart",
  // },
];
